name: dart_json_arb_json_converter
description: Convert json keys to arb notations and backward.
version: 0.0.1
homepage: https://github.com/AgoraDesk-LocalMonero/dart-json-arb-json-converter

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {args: ^2.3.1}
